(function() {
    var questions = [{
      question: "(ENEM - 2019) Uma pessoa se interessou em adquirir um produto anunciado em uma loja. Negociou com o gerente e conseguiu comprá-lo a uma taxa de juros compostos de 1% ao mês. O primeiro pagamento será em um mês após a aquisição do produto, e no valor de R$202,00. O segundo pagamento será efetuado em um mês após o primeiro, e terá o valor de R$204,02. Para concretizar a compra, o gerente emitirá uma nota fiscal com o valor do produto à vista negociado com o cliente, correspondendo ao financiamento aprovado. O valor à vista, em real, que deverá constar na nota fiscal é de:",
      choices: ["A) 398,02.", "B) 400,00.", "C) 401,94.", "D) 404,00.", "E) 406,02."]
    }, {
      question: "(ENEM - 2019) Em um jogo on-line, cada jogador procura subir de nível e aumentar sua experiência, que são dois parâmetros importantes no jogo, dos quais dependem as forças de defesa e ataque do participante. A força de defesa de cada jogador é diretamente proporcional ao seu nível e ao quadrado de sua experiência, enquanto sua força de ataque é diretamente proporcional à sua experiência e ao quadrado do seu nível. Nenhum jogador sabe o nível ou experiência dos demais. Os jogadores iniciam o jogo no nível 1 com experiência 1 e possuem força de ataque 2 e de defesa 1. Nesse jogo, cada participante se movimenta em uma cidade em busca de tesouros para aumentar sua experiência. Quando dois deles se encontram, um deles pode desafiar o outro para um confronto, sendo o desafiante considerado o atacante. Compara-se então a força de ataque do desafiante com a força de defesa do desafiado e vence o confronto aquele cuja força for maior. O vencedor do desafio aumenta seu nível em uma unidade. Caso haja empate no confronto, ambos os jogadores aumentam seus níveis em uma unidade. Durante o jogo, o jogador J1, de nível 4 e experiência 5, irá atacar o jogador J2, de nível 2 e experiência 6. O jogador J1 venceu esse confronto porque a diferença entre sua força de ataque e a força de defesa de seu oponente era:",
      choices: ["A) 112.", "B) 88.", "C) 60.", "D) 28.", "E) 24."]
    }, {
      question: "(Enem 2015) Segundo o Instituto Brasileiro de Geografia e Estatística (IBGE), produtos sazonais são aqueles que apresentam ciclo bem definidos de produção, consumo e preço. Resumidamente, existem épocas do ano em que a sua disponibilidade nos mercados varejistas ora é escassa, com preços elevados, ora é abundante, com preços mais baixos, o que ocorre no mês de produção máxima da safra. A partir de uma série histórica, observou-se que o preço P, em reais, do quilograma de um certo produto sazonal pode ser descrito pela função P(x)=8+5cos(πx−π6) onde x representa o mês do ano, sendo x = 1 associado ao mês de janeiro, x = 2 ao mês de fevereiro, e assim sucessivamente, até x = 12 associado ao mês de dezembro. Na safra, o mês de produção máxima desse produto é:",
      choices: ["A) janeiro.", "B) abril.", "C) junho.", "D) julho.", "E) outubro."]
    }, {
      question: "(ENEM - 2018) Os tipos de prata normalmente vendidos são 975, 950 e 925. Essa classificação é feita de acordo com a sua pureza. Por exemplo, a prata 975 é a substância constituída de 975 partes de prata pura e 25 partes de cobre em 1 000 partes da substância. Já a prata 950 é constituída de 950 partes de prata pura e 50 de cobre em 1 000; e  a prata 925 é constituída de 925 partes de prata  pura e 75 partes de cobre em 1 000. Um ourives possui 10 gramas de prata 925 e deseja obter 40 gramas de prata 950 para produção de uma joia. Nessas condições, quantos gramas de prata e de cobre, respectivamente, devem ser fundidos com os 10 gramas de prata 925?",
      choices: ["A) 29,25 e 0,75.", "B) 28,75 e 1,25.", "C) 28,50 e 1,50.", "D) 27,75 e 2,25.", "E) 25,00 e 5,00."]
    }, {
      question: "(Enem 2015) Uma competição esportiva envolveu 20 equipes com 10 atletas cada. Uma denúncia à organização dizia que um dos atletas havia utilizado substância proibida. Os organizadores, então, decidiram fazer um exame antidoping. Foram propostos três modos diferentes para escolher os atletas que irão realizá-lo: Modo I: sortear três atletas dentre todos os participantes; Modo II: sortear primeiro uma das equipes e, desta, sortear três atletas; Modo III: sortear primeiro três equipes e, então, sortear um atleta de cada uma dessas três equipes. Considere que todos os atletas têm igual probabilidade de serem sorteados e que P(I), P(II) e P(III) sejam as probabilidades de o atleta que utilizou a substância proibida seja um dos escolhidos para o exame no caso do sorteio ser feito pelo modo I, II ou III. Comparando-se essas probabilidades, obtém-se:",
      choices: ["A) P(I) < P(III) < P(II).", "B) P(I) < P(I) < P(III).", "C) P(I) < P(II) = P(III).", "D) P(I) = P(II) < P(III).", "E) P(I) = P(II) = P(III)."]
    }, {
      question: "(Enem 2015)  Em uma escola, a probabilidade de um aluno compreender e falar inglês é de 30%. Três alunos dessa escola, que estão em fase final de seleção de intercâmbio, aguardam, em uma sala, serem chamados para uma entrevista. Mas, ao invés de chamá-los um a um, o entrevistador entra na sala e faz, oralmente, uma pergunta em inglês que pode ser respondida por qualquer um dos alunos. A probabilidade de o entrevistador ser entendido e ter sua pergunta oralmente respondida em inglês é:",
      choices: ["A) 23,7%", "B) 30,0%", "C) 44,1%", "D) 65,7%", "E) 90,0%"]
    }, {
      question: "(ENEM - 2015) Alguns exames médicos requerem uma ingestão de água maior do que a habitual. Por recomendação médica, antes do horário do exame, uma paciente deveria ingerir 1 copo de água de 150 mililitros a cada meia hora, durante as 10 horas que antecederiam um exame. A paciente foi a um supermercado comprar água e verificou que havia  garrafas dos seguintes tipos: • Garrafa I: 0,15 litro • Garrafa II: 0,30 litro • Garrafa III: 0,75 litro • Garrafa IV: 1,50 litro • Garrafa V: 3,00 litros. A paciente decidiu comprar duas garrafas do mesmo tipo, procurando atender à recomendação médica e, ainda, de modo a consumir todo o líquido das duas garrafas antes do exame. Qual o tipo de garrafa escolhida pela paciente?",
      choices: ["A) I.", "B) II.", "C) III.", "D) IV.", "E) V."]
    }, {
      question: "(Enem 2015) Segundo dados apurados no Censo 2010, para uma população de 101,8 milhões de brasileiros com 10 anos ou mais de idade e que teve algum tipo de rendimento em 2010, a renda média mensal apurada foi de R$ 1 202,00. A soma dos rendimentos mensais dos 10% mais pobres correspondeu a apenas 1,1% do total de rendimentos dessa população considerada, enquanto que a soma dos rendimentos mensais dos 10% mais ricos correspondeu a 44,5% desse total. Qual foi a diferença, em reais, entre a renda média mensal de um brasileiro que estava na faixa dos 10% mais ricos e de um brasileiro que estava na faixa dos 10% mais pobres?",
      choices: ["A) 240,40.", "B) 548,11.", "C) 1 723,67.", "D) 4 026,70.", "E) 5 216,68."]
    }, {
      question: "(ENEM - 2015) As exportações de soja do Brasil totalizaram 4,129 milhões de toneladas no mês de julho de 2012, e registraram um aumento em relação ao mês de julho de 2011, embora tenha havido uma baixa em relação ao mês de maio de 2012. A quantidade, em quilogramas, de soja exportada pelo Brasil no mês de julho de 2012 foi de:",
      choices: ["A) 4,129 x 103.", "B) 4,129 x 106.", "C) 4,129 x 109.", "D) 4,129 x 1012.", "E) 4,129 x 1015."]
    }, {
      question: "(Enem 2015) O HPV é uma doença sexualmente transmissível. Uma vacina com eficácia de 98% foi criada com objetivo de prevenir a infecção por HPV e, dessa forma, reduzir o número de pessoas que venham a desenvolver câncer de colo de útero. Uma campanha de vacinação foi lançada em 2014 pelo SUS, para um público-alvo de meninas de 11 a 13 anos de idade. Considera-se que, em uma população não vacinada, o HPV acomete 50% desse público ao longo de suas vidas. Em certo município, a equipe coordenadora da campanha decidiu vacinar meninas entre 11 e 13 anos de idade em quantidade suficiente para que a probabilidade de uma menina nessa faixa etária, escolhida ao acaso, vir a desenvolver essa doença seja, no máximo, de 5,9%. Houve cinco propostas de cobertura, de modo a atingir essa meta: Proposta I: vacinação de 90% do público-alvo. Proposta II: vacinação de 55,8% do público-alvo. Proposta III: vacinação de 88,2% do público-alvo. Proposta IV: vacinação de 49% do público-alvo. Proposta V: vacinação de 95,9% do público-alvo. Para diminuir os custos, a proposta escolhida deveria ser também aquela que vacinasse a menor quantidade possível de pessoas. A proposta implementada foi a de número:",
      choices: ["A) I.", "B) II.", "C) III.", "D) IV.", "E) V."]
    }, {
      question: "(ENEM - 2015)  Um casal realiza um financiamento imobiliário de R$ 180 000,00, a ser pago em 360 prestações mensais  com taxa de juros efetiva de 1% ao mês. A primeira prestação é paga um mês após a liberação dos recursos e o valor da prestação mensal é de R$ 500,00 mais juros de 1% sobre o saldo devedor (valor devido antes do pagamento). Observe que, a cada pagamento, o saldo devedor se reduz em R$ 500,00 e considere que não há prestação em atraso. Efetuando o pagamento dessa forma, o valor, em reais, a ser pago ao banco na décima prestação é de:",
      choices: ["A) 2 075,00.", "B) 2 093,00.", "C) 2 138,00.", "D) 2 255,00.", "E) 2 300,00."]
    }, {
      question: "(Enem 2015) Uma padaria vende, em média, 100 pães especiais por dia e arrecada com essas vendas, em média, R$ 300,00. Constatou-se que a quantidade de pães especiais vendidos diariamente aumenta, caso o preço seja reduzido, de acordo com a equação q = 400 – 100p, na qual q representa a quantidade de pães especiais vendidos diariamente e p, o seu preço em reais. A fim de aumentar o fluxo de clientes, o gerente da padaria decidiu fazer uma promoção. Para tanto, modificará o preço do pão especial de modo que a quantidade a ser vendida diariamente seja a maior possível, sem diminuir a média de arrecadação diária na venda desse produto. O preço p, em reais, do pão especial nessa promoção deverá estar no intervalo:",
      choices: ["A) R$ 0, 50 ≤ p < R$ 1, 50.", "B) R$ 1, 50 ≤ p < R$ 2, 50.", "C) R$ 2, 50 ≤ p < R$ 3, 50.", "D) R$ 3, 50 ≤ p < R$ 4, 50.", "E) R$ 4, 50 ≤ p < R$ 5, 50."]
    }, {
      question: "(ENEM) O potencial brasileiro para transformar lixo em energia permanece subutilizado — apenas pequena parte dos resíduos brasileiros é utilizada para gerar energia. Contudo, bons exemplos são os aterros sanitários, que utilizam a principal fonte de energia ali produzida. Alguns aterros vendem créditos de carbono com base no mecanismo de Desenvolvimento Limpo (MDL), do Protocolo de Kyoto. Essa fonte de energia subutilizada, citada no texto, é o:",
      choices: ["A) etanol, obtido a partir da decomposição da matéria orgânica por bactérias.", "B) gás natural, formado pela ação de fungos decompositores da matéria orgânica.", "C) óleo de xisto, obtido pela decomposição da matéria orgânica pelas bactérias anaeróbias.", "D) gás metano, obtido pela atividade de bactérias anaeróbias na decomposição da matéria              orgânica.", "E) gás liquefeito de petróleo, obtido pela decomposição de vegetais presentes nos restos de              comida."]
    }, {
      question: "(UNICAMP) “Pode arredondar?” Esta é uma pergunta que frentistas de postos de combustíveis fazem durante o abastecimento, quando o travamento automático da bomba é acionado. O fabricante do veículo faz a recomendação de não arredondar, pensando na preservação do veículo, mas o dono do posto pede que o frentista arredonde, para vender mais combustível. Por outro lado, pensando na saúde do frentista, prejudicada pela exposição aos vapores de combustível, pode-se afirmar corretamente que:",
      choices: ["A) Qualquer que seja a resposta do consumidor, até o travamento automático ou passando do automático, a saúde do frentista será prejudicada, pois sempre haverá eliminação de vapores durante o abastecimento.", "B) A resposta mais adequada do consumidor seria “sim”, porque a quantidade de vapores eliminados no abastecimento é a mesma, e o prejuízo à saúde do frentista é o mesmo, independentemente do volume de combustível adicionado ao tanque.", "C) A resposta mais adequada do consumidor seria “não”, pois somente a partir do travamento automático é que há eliminação de vapores durante o abastecimento e só depois disso há prejuízo para a saúde do frentista.", "D) A resposta mais adequada do consumidor seria “sim”, porque não haverá eliminação de vapores durante o abastecimento e assim nunca haverá prejuízo para a saúde do frentista."]
    }, {
      question: "(ENEM) O petróleo é uma fonte de energia de baixo  custo e de larga utilização como matéria-prima para uma grande variedade de produtos. É um óleo formado de várias substâncias de origem orgânica, em sua maioria hidrocarbonetos de diferentes massas molares. São utilizadas técnicas de separação para obtenção dos componentes comercializáveis do petróleo. Além disso, para aumentar a quantidade de frações comercializáveis, otimizando o produto de origem fóssil, utiliza-se o processo de craqueamento. O que ocorre nesse processo?",
      choices: ["A) Transformação das frações do petróleo em outras moléculas menores.", "B) Reação de óxido-redução com transferência de elétrons entre as moléculas.", "C) Solubilização das frações do petróleo com a utilização de diferentes solventes.", "D) Decantação das moléculas com diferentes massas molares pelo uso de centrífugas.", "E) Separação dos diferentes componentes do petróleo em função de suas temperaturas de ebulição."]
    }, {
      question: "(UNICAMP) O vazamento de petróleo no Golfo do México, em abril de 2010, foi considerado o pior da história dos EUA. O vazamento causou o aparecimento de uma extensa mancha de óleo na superfície do oceano, ameaçando a fauna e a flora da região. Estima-se que o vazamento foi da ordem de 800 milhões de litros de petróleo em cerca de 100 dias. Por ocasião do acidente, cogitou-se que todo o óleo vazado poderia ser queimado na superfície da água. Se esse procedimento fosse adotado, o dano ambiental:",
      choices: ["A) não seria grave, pois o petróleo é formado somente por compostos de carbono e hidrogênio, que, na queima, formariam CO2 e água.", "B) seria mais grave ainda, já que a quantidade (em mols) de CO2 formada seria bem maior que a quantidade (em mols) de carbono presente nas substâncias do petróleo queimado.", "C) seria praticamente nulo, pois a diversidade de vida no ar atmosférico é muito pequena.", "D) seria transferido da água do mar para o ar atmosférico."]
    }, {
      question: "(ENEM) Pesquisadores recuperaram DNA de ossos de mamute (Mammuthus primigenius) encontrados na Sibérica, que tiveram sua idade de cerca de 28 mil anos confirmada pela técnica do carbono 14. Fapesp. DNA de mamute é revelado. A técnica e datação apresentada no texto só é possível devido à:",
      choices: ["A) proporção conhecidada entre carbono-14 e carbono-12 na atmosfera ao longo dos anos.", "B) decomposição de todo o carbono-12 presente no organismo após a morte.", "C) fixação maior do carbono-14 nos tecidos de organismos após a morte.", "D) emissão de carbono-12 pelos tecidos de organismos após a morte.", "E) transformação do carbono-12 em crbono -14 ao longo dos anos."]
    }, {
      question: "(UEFS) O petróleo é fonte de combustíveis e de matérias-primas industriais que são obtidos pela destilação fracionada nas refinarias. Entretanto, o aumento na extração do petróleo, do efeito estufa e da poluição ambiental, decorrentes do uso contínuo de combustíveis de origem fóssil, vêm sendo discutidos por toda a sociedade. Considerando-se essas informações associadas aos conhecimentos da Química, é correto afirmar:",
      choices: ["A) A liberação de SO2(g) na queima de combustíveis, como o óleo diesel, é inócuo ao ambiente porque esse gás é instável e reage rapidamente com o oxigênio do ar.", "B) O aumento na extração de petróleo não compromete as grandes reservas mundiais, porque esse material é formado pela decomposição aeróbica de materiais orgânicos.", "C) O efeito estufa está relacionado à capacidade de o dióxido de carbono, CO2(g), produto da combustão completa, absorver a radiação ultravioleta proveniente do Sol.", "D) O óleo diesel, mistura de hidrocarbonetos constituídos por cadeias carbônicas com 13 a 17 átomos de carbono, é um líquido menos denso do que a gasolina comum.", "E) A obtenção de polímeros sintéticos, usados na fabricação de tecidos, colas e embalagens plásticas, requer a utilização de matérias-primas obtidas na destilação do petróleo."]
    }, {
      question: "(ENEM) No final do século XX e em razão dos avanços da ciência, produziu-se um sistema presidido pelas técnicas da informação, que passaram a exercer um papel de elo entre as demais, unindo-as e assegurando ao novo sistema uma presença planetária. Um mercado que utiliza esse sistema de técnicas avançadas resulta nessa globalização perversa. SANTOS, M. Por uma outra Globalização. Rio de Janeiro: Record, 2008 (adaptado) Uma consequência para o setor produtivo e outra para o mundo do trabalho advindas das transformações citadas no texto estão presentes, respectivamente, em:",
      choices: ["A) Eliminação das vantagens locacionais e ampliação da legislação laboral.", "B) Limitação dos fluxos logísticos e fortalecimento de associações sindicais.", "C) Diminuição dos investimentos industriais e desvalorização dos postos qualificados.", "D) Concentração das áreas manufatureiras e redução da jornada semanal.", "E) Automatização dos processos fabris e aumento dos níveis de desemprego."]
    }, {
      question: "(ENEM) A geografia mundial da inovação sofreu uma reviravolta que mobiliza fatores humanos, financeiros e tecnológicos. Esforço humano: com milhão de pesquisadores, a China dispõe de um potencial equivalente a da capacidade norte-americana e da europeia; segundo a National Science Foundation norte-americana, o país deverá concentrar de todos os pesquisadores do mundo até 2025. Esforço financeiro: em 2009, pela primeira vez, a China apresentou um orçamento para pesquisa que a colocou em segundo lugar no mundo – ainda bastante longe dos Estados Unidos, mas à frente do Japão. Esforço tecnológico: em 2011, o país se tornou o primeiro depositante mundial de patentes, graças a uma estratégia nacional que visa passar do Made in China (produzido na China) para o Designed in China(projetado na China). O texto apresenta um novo fator a ser considerado para refletir sobre o papel produtivo entre os países, representado pela:",
      choices: ["A) aplicação da ciência e tecnologia no desenvolvimento produtivo, que aumenta o potencial inventivo.", "B) ampliação da capacidade da indústria de base, que coopera para diversificar os níveis produtivos.", "C) exploração da mão de obra, que atrai fluxo de investimentos industriais para os países.", "D) inserção de pesquisas aplicadas ao setor financeiro, que incentiva a livre concorrência.", "E) transnacionalização do capital industrial, que eleva os lucros em escala planetária."]
    }, {
      question: "Um carro esportivo é financiado pelo Japão, projetado na Itália e montado em Indiana, México e França, usando os mais avançados componentes eletrônicos, que foram inventados em Nova Jérsei e fabricados na Coreia. A campanha publicitária é desenvolvida na Inglaterra, filmada no Canadá, a edição e as cópias, feitas em Nova York para serem veiculadas no mundo todo. Teias globais disfarçam-se com o uniforme nacional que lhes for mais conveniente. REICH, R. O trabalho das nações: preparando-nos para o capitalismo no século XXI. São Paulo: Educator, 1994 (adaptado). A viabilidade do processo de produção ilustrado pelo texto pressupõe o uso de:",
      choices: ["A) linhas de montagem e formação de estoques.", "B) empresas burocráticas e mão de obra barata.", "C) controle estatal e infraestrutura consolidada.", "D) organização em rede e tecnologia de informação.", "E) gestão centralizada e protecionismo econômico."]
    }, {
      question: "(ENEM) A mundialização introduz o aumento da produtividade do trabalho sem acumulação de capital, justamente pelo caráter divisível da forma técnica molecular digital do que resulta a permanência da má distribuição da renda: exemplificando mais uma vez, os vendedores de refrigerantes às portas dos estádios viram sua produtividade aumentada graças ao just in time dos fabricantes e distribuidores de bebidas, mas para realizar o valor de tais mercadorias, a forma do trabalho dos vendedores é a mais primitiva. Combinam-se, pois, acumulação molecular-digital com o puro uso da força de trabalho. OLIVEIRA, F. Crítica à razão dualista e o ornitorrinco. Campinas Boitempo, 2003. Os aspectos destacados no texto afetam diretamente questões como emprego e renda, sendo possível explicar essas transformações pelo(a):",
      choices: ["A) crise bancária e o fortalecimento do capital industrial.", "B) inovação toyotista e a regularização do trabalho formal.", "C) impacto da tecnologia e as modificações na estrutura produtiva.", "D) emergência da globalização e a expansão do setor secundário.", "E) diminuição do tempo de trabalho e a necessidade do diploma superior."]
    }, {
      question: "(UFPA) A atividade industrial e a industrialização brasileira estão desigualmente distribuídas pelas regiões do país. Construídas predominantemente no século XX, elas são componentes da modernização urbana que reinventa nossa sociedade e dinâmica espacial. Sobre a indústria e industrialização brasileira, é correto afirmar:",
      choices: ["A) A industrialização tem suas raízes fincadas na economia da cana-de-açúcar e do café. que possibilitou a acumulação de capital necessária para a diversificação em investimentos no setor industrial, e esse fato permitiu a produção de bens de consumo duráveis, sobretudo automóveis e eletrodomésticos.", "B) A indústria nasce dos capitais restantes do declínio da economia da cana-de-açúcar e do café. Esses capitais impulsionaram uma diversidade de pequenas indústrias de produção de bens de consumo não duráveis, tais como perfumaria, cosméticos, bebidas, cigarros, que apoiadas pelo Estado se difundiram pelo país", "C) A ação do Estado foi fundamental para desencadear o processo de industrialização brasileira. por exemplo. criando empresas estatais, como a antiga Companhia Vale do Rio Doce e a Companhia Siderúrgica Nacional, para investir na indústria de base. Sem elas não seria possível a implantação de indústria de bens de consumo duráveis.", "D) A industrialização brasileira é fruto da capacidade inovadora do Estado e do empresariado nacional. Este último não mediu esforços para construir em todo o território nacional sistemas de transporte, comunicação, energia e portos, necessários à circulação de bens, serviços e pessoas por todas as regiões.", "E) A industrialização brasileira se tornou possível a partir de investimentos do capital internacional, que não mediu esforços para construir em todo o território nacional sistemas de transporte, comunicação, energia e portos, necessários a circulação de bens, serviços e pessoas por todas as regiões."]
    }, {
      question: "(ENEM) A partir dos anos 70, impõe-se um movimento de desconcentração da produção industrial, uma das manifestações do desdobramento da divisão territorial do trabalho no Brasil. A produção industrial torna-se mais complexa, estendendo-se, sobretudo, para novas áreas do Sul e para alguns pontos do Centro-Oeste, do Nordeste e do Norte. SANTOS, M.; SILVEIRA, M. L. O Brasil: território e sociedade no início do século XXI. Rio de Janeiro: Record, 2002 (fragmento). Um fator geográfico que contribui para o tipo de alteração da configuração territorial descrito no texto é:",
      choices: ["A) Obsolescência dos portos.", "B) Estatização de empresas.", "C) Eliminação de incentivos fiscais.", "D) Ampliação de políticas protecionistas.", "E) Desenvolvimento dos meios de comunicação."]
    }, {
      question: "(UNESP) Uma mesma empresa pode ter sua sede administrativa onde os impostos são menores, as unidades de produção onde os salários são os mais baixos, os capitais onde os juros são os mais altos e seus executivos vivendo onde a qualidade de vida é mais elevada. SEVCENKO, N. A corrida para o século XXI: no loop da montanha russa. São Paulo: Companhia das Letras, 2001 (adaptado). No texto estão apresentadas estratégias empresariais no contexto da globalização. Uma consequência social derivada dessas estratégias tem sido:",
      choices: ["A) o crescimento da carga tributária.", "B) o aumento da mobilidade ocupacional.", "C) a redução da competitividade entre as empresas.", "D) o direcionamento das vendas para os mercados regionais.", "E) a ampliação do poder de planejamento dos Estados nacionais."]
    }, {
      question: "(UEA) No contexto da revolução técnico-científica, governantes e empresas de países desenvolvidos, como Estados Unidos, Canadá, Alemanha, França e Japão, têm estimulado a criação de arranjos territoriais chamados tecnopolos, caracterizados por:",
      choices: ["A) centros tecnológicos de pesquisa e desenvolvimento que apresentam concentração de mão de obra qualificada capaz de gerar novos produtos de alta tecnologia que poderão ser absorvidos pelas indústrias.", "B) centros tecnológicos de pesquisa e desenvolvimento instalados em fazendas que utilizam ferramentas tradicionais e mão de obra intensiva para realizar estudos que aumentem a produtividade.", "C) áreas centrais das grandes cidades que apresentam alta concentração de compra e venda de produtos tecnológicos e serviços de manutenção com mão de obra pouco qualificada.", "D) conjuntos empresariais voltados para a prestação de serviços avançados a distância com o emprego de mão de obra barata adaptada ao uso de sistemas de comunicação e informação.", "E) áreas centrais das grandes metrópoles que apresentam elevado dinamismo para a recepção de eventos e congressos especializados em biotecnologia e saúde para soluções de demandas em mercados emergentes."]
    }, {
      question: "(ENEM) A radioterapia é um método capaz de destruir células tumorais, empregando feixe de radiações ionizantes. Uma dose pré-calculada de radiação é aplicada, buscando destruir as células tumorais, com o menor dano possível às células normais circunvizinhas. A resposta dos tecidos às radiações depende de diversos fatores, entre eles a oxigenação. Em termos práticos isto quer dizer que, para um mesmo efeito, em condições de hipoxia (baixa oxigenação) é necessária uma dose de irradiação 2,5 a 3,5 vezes superior à que seria indicada em condições de oxigenação normais, o que seria letal. Considerando essas informações, pode-se deduzir que a aplicação desse procedimento está contraindicada na situação de:",
      choices: ["A) anemia.", "B) basofilia.", "C) eosinofilia.", "D) linfocitose.", "E) leucopenia."]
    }, {
      question: "(ENEM) A perda de pelos foi uma adaptação às mudanças ambientais, que forçaram nossos ancestrais a deixar a vida sedentária e viajar enormes distâncias à procura de água e comida. Junto com o surgimento de membros mais alongados e com a substituição de glândulas apócrinas (produtoras de suor oleoso e de lenta evaporação) por glândulas écrinas (suor aquoso e de rápida evaporação), a menor quantidade de pelos teria favorecido a manutenção de uma temperatura corporal saudável nos trópicos castigados por calor sufocante, em que viveram nossos ancestrais. Scientific American. Brasil, mar. 2010 (adaptado). De que maneira o tamanho dos membros humanos poderia estar associado à regulação da temperatura corporal?",
      choices: ["A) Membros mais longos apresentam maior relação superfície/volume, facilitando a perda de maior quantidade de calor.", "B) Membros mais curtos têm ossos mais espessos, que protegem vasos sanguíneos contra a perda de calor.", "C) Membros mais curtos desenvolvem mais o panículo adiposo, sendo capazes de reter maior quantidade de calor.", "D) Membros mais longos possuem pele mais fina e com menos pelos, facilitando a perda de maior quantidade de calor.", "E) Membros mais longos têm maior massa muscular, capazes de produzir e dissipar maior quantidade de calor."]
    }, {
      question: "(MACKENZIE) Muitos seres vivos produzem substâncias que afetam o funcionamento do sistema nervoso humano. Dessa forma, vários medicamentos são elaborados a partir de substâncias produzidas, por exemplo, por fungos ou plantas. É correto afirmar que:",
      choices: ["A) essas substâncias são inofensivas aos seres humanos, uma vez que são produzidas por outros seres vivos.", "B) essas substâncias podem agir durante um tempo, mas são sempre metabolizadas e não afetam permanentemente o funcionamento do sistema nervoso humano.", "C) essas substâncias podem agir na geração, condução ou transmissão do impulso nervoso.", "D) a intensidade da resposta nervosa a essas substâncias depende exclusivamente da dose utilizada.", "E) cada substância provoca apenas um tipo de resposta, sendo, assim, específica para cada região do sistema nervoso."]
    }, {
      question: "(UFES) A força humana está relacionada diretamente com os músculos, e, para que estes realizem trabalho, é necessário que ocorra a contração muscular. Sobre os mecanismos envolvidos na contração muscular, pode-se afirmar que:",
      choices: ["A) a miosina é responsável pela conversão da energia da hidrólise do ATP em movimento, devido à presença dos íons de ferro.", "B) a quimiossíntese ocorre nas células musculares, onde o ácido pirúvico é transformado em ácido lático, o que garante ATP em situações de emergência.", "C) o deslizamento durante a contração muscular ocorre quando as cabeças da miosina se prendem firmemente à actina, dobrando-se sobre o resto da molécula da miosina e permanecendo assim indefinidamente.", "D) o glicogênio armazenado nas células musculares pode ser convertido em ATP por meio de processos de fermentação alcoólica, o que causa dor e intoxicação das fibras musculares.", "E) a energia obtida do ATP confere à miosina uma configuração instável de alta energia potencial e faz com que ela puxe as fibras de actina, realizando o trabalho."]
    }, {
      question: "(UFF) O sistema imune apresenta um tipo de célula que passa do vaso sanguíneo para o tecido conjuntivo onde irá exercer sua função de defesa. A célula e a passagem são, respectivamente, identificadas como:",
      choices: ["A) basôfilos e pinocitose.", "B) macrófagos e fagocitose.", "C) leucócitos e endocitose.", "D) leucócitos e diapedese.", "E) glóbulos brancos e endocitose."]
    }, {
      question: "(UECE) Na cadeia de propagação do impulso nervoso, na ordem de passagem do impulso pelo neurônio, podemos afirmar corretamente que o corpo celular é a estrutura neuronal que o recebe",
      choices: ["A) por último, passando-o para um novo neurônio.", "B) intermediariamente, passando-o para o dendrito.", "C) primeiro, passando-o para o axônio.", "D) intermediariamente, passando-o para o axônio."]
    }, {
      question: "(Enem) Em discurso proferido em 17 de março de 1939, o primeiro-ministro inglês à época, Neville Chamberlain, sustentou sua posição política: “Não necessito defender minhas visitas à Alemanha no outono passado, que alternativa existia? Nada do que pudéssemos ter feito, nada do que a França pudesse ter feito, ou mesmo a Rússia, teria salvado a Tchecoslováquia da destruição. Mas eu também tinha outro propósito ao ir até Munique. Era o de prosseguir com a política por vezes chamada de ‘apaziguamento europeu’, e Hitler repetiu o que já havia dito, ou seja, que os Sudetos, região de população alemã na Tchecoslováquia, eram a sua última ambição territorial na Europa, e que não queria incluir na Alemanha outros povos que não os alemães.”Sabendo-se que o compromisso assumido por Hitler em 1938, mencionado no texto acima, foi rompido pelo líder alemão em 1939, infere-se que:",
      choices: ["A) Hitler ambicionava o controle de mais territórios na Europa além da região dos Sudetos.", "B) a aliança entre a Inglaterra, a França e a Rússia poderia ter salvado a Tchecoslováquia.", "C) o rompimento desse compromisso inspirou a política de ‘apaziguamento europeu’.", "D) a política de Chamberlain de apaziguar o líder alemão era contrária à posição assumida pelas potências aliadas.", "E) a forma que Chamberlain escolheu para lidar com o problema dos Sudetos deu origem à destruição da Tchecoslováquia."]
    }, {
      question: "(Enem) Quanto aos campos de batalha, os nomes de ilhas melanésias e assentamentos nos desertos norte-africanos, na Birmânia e nas Filipinas, tornaram-se tão conhecidos dos leitores de jornais e radiouvintes quanto os nomes de batalhas no Ártico e no Cáucaso, na Normandia, em Stalingrado e em Kursk. A Segunda Guerra Mundial foi uma aula de geografia. Um dos principais acontecimentos do século XX, a Segunda Grande Guerra (1939-1945) foi interpretada no texto como uma aula de geografia porque:",
      choices: ["A) teve-se ciência de lugares outrora ignorados.", "B) foram modificadas fronteiras e relações interestatais.", "C) utilizaram mapas estratégicos os exércitos nela envolvidos.", "D) tratou-se de um acontecimento que afetou a economia global.", "E) tornou o continente europeu o centro das relações internacionais."]
    }, {
      question: "(Enem/2018) A rebelião luso-brasileira em Pernambuco começou a ser urdida em 1644 e explodiu em 13 de junho de 1645, dia de Santo Antônio. Uma das primeiras medidas de João Fernandes foi decretar nulas as dívidas que os rebeldes tinham com os holandeses. Houve grande adesão da “nobreza da terra”, entusiasmada com esta proclamação heroica. O desencadeamento dessa revolta na América portuguesa seiscentista foi o resultado do(a):",
      choices: ["A) fraqueza bélica dos protestantes batavos.", "B) comércio transatlântico da África ocidental.", "C) auxílio financeiro dos negociantes flamengos.", "D) diplomacia internacional dos Estados ibéricos.", "E) interesse econômico dos senhores de engenho."]
    }, {
      question: "(Enem/2017) Sou filho natural de uma negra, africana livre, da Costa da Mina (Nagô de Nação), de nome Luíza Mahin, pagã, que sempre recusou o batismo e a doutrina cristã. Minha mãe era baixa de estatura, magra, bonita, a cor era de um preto retinto e sem lustro, tinha os dentes alvíssimos como a neve, era muito altiva, geniosa, insofrida. Dava-se ao comércio – era quitandeira, muito laboriosa e, mais de uma vez, na Bahia, foi presa como suspeita de envolver-se em planos de insurreição de escravos, que não tiveram efeito. Nesse trecho de suas memórias, Luiz Gama ressalta a importância dos(as):",
      choices: ["A) laços de solidariedade familiar.", "B) estratégias de resistência cultural.", "C) mecanismos de hierarquização tribal.", "D) instrumentos de dominação religiosa.", "E) limites da concessão de alforria."]
    }, {
      question: "(Unisc/2014) Em 2014 completará 50 anos do Golpe que depôs o governo de João Goulart e instalou o Regime Militar no Brasil. A Ditadura permaneceu por mais de vinte anos não permitindo eleições livres para presidente e controlando muito de perto os sindicatos, movimentos sociais e outros grupos que questionavam a falta de democracia e a truculência do Regime por meio dos aparatos de repressão. Sobre esse período é INCORRETO afirmar que:",
      choices: ["A) o pluripartidarismo foi extinto no Ato Institucional n. 2 que permitiu apenas dois partidos – ARENA e MDB.", "B) o Ato Institucional n. 5 limitou ainda mais os direitos políticos no Brasil cassando políticos considerados pelo Regime como subversivos.", "C) a censura foi imposta logo após o Golpe Militar e teve como o Serviço Nacional de Informações (SNI) seu órgão mais atuante.", "D) a propaganda pró-regime militar usou slogans como Brasil – ame-o ou deixe-o.", "E) o último presidente militar, Costa e Silva, prometeu uma abertura política para a democracia de forma lenta e gradual."]
    }, {
      question: "(Unitau/2018) No cabeçalho do Jornal do Brasil, do dia 14 de dezembro de 1968, aparecia escrito: “Tempo negro. Temperatura sufocante. O ar está irrespirável. O país está sendo varrido por fortes ventos. Máx: 38º em Brasília, Mín: 5º, nas Laranjeiras”. A qual fato esse texto faz referência?",
      choices: ["A) Aprovação do Ato Institucional nº 5, que limitou drasticamente a liberdade de expressão e instituiu medidas que ampliaram a repressão aos opositores do governo militar.", "B) Aprovação do Ato Institucional nº 2, aprovado pelo Congresso Nacional, que ampliou o medo do perigo comunista.", "C) Aprovação da Lei da Censura Federativa, do Ato Institucional nº 1, que coibiu filmes, peças teatrais, livros, músicas, mas que não chegou ao jornal e, por isso, a crítica foi publicada em primeira página.", "D) Aprovação dos atos institucionais, que tiveram grande apoio de classes políticas do país, ampliando várias garantias individuais e conferindo amplos poderes ao presidente da República.", "E) Aprovação do bipartidarismo, por meio do Ato Institucional nº 1, que eliminou toda forma de oposição institucional ao regime militar."]
    }, {
      question: "(Enem/2017) Nos primeiros anos do governo Vargas, as organizações operárias sob controle das correntes de esquerda tentaram se opor ao seu enquadramento pelo Estado. Mas a tentativa fracassou. Além do governo, a própria base dessas organizações pressionou pela legalização. Vários benefícios, como as férias e a possibilidade de postular direitos perante às Juntas de Conciliação e Julgamento, dependiam da condição de ser membro de sindicato reconhecido pelo governo. FAUSTO, B. História concisa do Brasil. São Paulo: Edusp; Imprensa Oficial do Estado, 2002 (adaptado). No contexto histórico retratado pelo texto, a relação entre governo e movimento sindical foi caracterizada:",
      choices: ["A) pelo reconhecimento de diferentes ideologias políticas.", "B) por um diálogo democraticamente constituído.", "C) pelas benesses sociais do getulismo.", "D) pela vinculação de direitos trabalhistas à tutela do Estado.", "E) por uma legislação construída consensualmente."]
    }, {
      question: "(Enem/2017) Estão aí, como se sabe, dois candidatos à presidência, os senhores Eduardo Gomes e Eurico Dutra, e um terceiro, o senhor Getúlio Vargas, que deve ser candidato de algum grupo político oculto, mas é também o candidato popular. Porque há dois “queremos”: o “queremos” dos que querem ver se continuam nas posições e o “queremos” popular… Afinal, o que é que o senhor Getúlio Vargas é? É fascista? É comunista? É ateu? É cristão? Quer sair? Quer ficar? O povo, entretanto, parece que gosta dele por isso mesmo, porque ele é “à moda da casa”. O movimento político mencionado no texto caracterizou-se por:",
      choices: ["A) demandar a confirmação dos direitos trabalhistas.", "B) apoiar a permanência da ditadura estadonovista.", "C) resgatar a representatividade dos sindicatos sob controle social.", "D) reivindicar a transição constitucional sob influência do governante.", "E) reclamar a participação das agremiações partidárias."]
    }, {
      question: "(ENEM 2015)A questão ambiental, uma das principais pautas contemporâneas, possibilitou o surgimento de concepções políticas diversas, dentre as quais se destaca a preservação ambiental, que sugere uma ideia de intocabilidade da natureza e impede o seu aproveitamento econômico sob qualquer justificativa. Considerando as atuais concepções políticas sobre a questão ambiental, a dinâmica caracterizada no texto quanto à proteção do meio ambiente está baseada na:",
      choices: ["A) prática econômica sustentável.", "B) contenção de impactos ambientais.", "C) utilização progressiva dos recursos naturais.", "D) proibição permanente da exploração da natureza.", "E) definição de áreas prioritárias para a exploração econômica."]
    }, {
      question: "(UFPA 2012) Se considerarmos que existe uma relação direta entre a crise ambiental que o planeta enfrenta atualmente e a lógica da acumulação capitalista, qual das afirmações abaixo NÃO JUSTIFICA esta afirmação?",
      choices: ["A) as estruturas de poder que controlam o uso dos recursos naturais e do meio ambiente comum estão baseadas no cálculo econômico privado das empresas, e este cálculo não considera as condições globais do meio ambiente, mas apenas os elementos mercantis.", "B) vivemos o risco de ruptura do equilíbrio ecológico do planeta pela incapacidade de os agentes econômicos se ajustarem às capacidades limitadas de suporte do meio ambiente.", "C) existem dois fatores de extrema importância que atuam simultaneamente no sentido do agravamento da crise ambiental: a concentração crescente do controle sobre os recursos naturais e a privatização do uso do meio ambiente comum.", "D) a solução da crise ambiental passa pela democratização do controle sobre os recursos naturais e pela desprivatização do meio ambiente comum, de tal forma que o acesso aos recursos naturais expressa uma vivência democrática efetiva.", "E) as proposições relativas à determinação de um elemento da sociedade por outro, como, por exemplo, a crise ambiental decorrente da forma como se dá a exploração econômica, não devem ser seriamente consideradas, pois há uma infinidade de outras causas não econômicas para a crise ambiental."]
    }, {
      question: "(Enem-2015) Não acho que seja possível identificar a globalização apenas com a criação de uma economia global, embora este seja seu ponto focal e sua característica mais óbvia. Precisamos olhar além da economia. Antes de tudo, a globalização depende da eliminação de obstáculos técnicos, não de obstáculos econômicos. Isso tornou possível organizar a produção, e não apenas o comércio, em escala internacional. HOBSBAWM, E. O novo século: entrevista a Antonio Polito. São Paulo: Cia. das Letras, 2000 (adaptado). Um fator essencial para a organização da produção, na conjuntura destacada no texto, é a:",
      choices: ["A) criação de uniões aduaneiras.", "B) difusão de padrões culturais.", "C) melhoria na infraestrutura de transportes.", "D) supressão das barreiras para comercialização.", "E) organização de regras nas relações internacionais."]
    }, {
      question: "(Enem-2015) No final do século XX e em razão dos avanços da ciência, produziu-se um sistema presidido pelas técnicas da informação, que passaram a exercer um papel de elo entre as demais, unindo-as e assegurando ao novo sistema uma presença planetária. Um mercado que utiliza esse sistema de técnicas avançadas resulta nessa globalização perversa. SANTOS, M. Por uma outra globalização. Rio de Janeiro: Record, 2008 (adaptado). Uma consequência para o setor produtivo e outra para o mundo do trabalho advindas das transformações citadas no texto estão presentes, respectivamente, em:",
      choices: ["A) Eliminação das vantagens locacionais e ampliação da legislação laboral.", "B) Limitação dos fluxos logísticos e fortalecimento de associações sindicais.", "C) Diminuição dos investimentos industriais e desvalorização dos postos qualificados.", "D) Concentração das áreas manufatureiras e redução da jornada semanal.", "E) Automatização dos processos fabris e aumento dos níveis de desemprego."]
    }, {
      question: "(Enem 2015 – modificada) O intemperismo físico é alteração que um ambiente sofre por causa das bruscas variações de umidade e temperatura, sendo a água seu principal agente. De acordo com as informações, é de esperar que um intemperismo mais fraco seja característica de qual tipo climático?",
      choices: ["A) Tropical.", "B) Litorâneo.", "C) Equatorial.", "D) Semiárido.", "E) Subtropical."]
    }, {
      question: "(FUNDATEC 2020) A Terra é conhecida como um “radiador” de corpo frio que emite energia em comprimentos de onda longos de sua superfície e atmosfera em direção ao espaço. No entanto, parte dessa radiação em ondas longas é absorvida por dióxido de carbono, vapor d’água, metano, óxido nitroso, entre outros, e posteriormente é emitida de volta para a Terra. Esse processo é denominado de Efeito:",
      choices: ["A) Smog.", "B) Coriolis.", "C) Estufa.", "D) Radioativo.", "E) Atmosférico."]
    }, {
      question: "(ENEM 2016) Os ecossistemas degradados por intensa atividade agrícola apresentam, geralmente, diminuição de sua diversidade e perda de sua estabilidade. Nesse contexto, o uso integrado de árvores aos sistemas agrícolas (sistemas agroflorestais) pode cumprir um papel inovador ao buscar a aceleração do processo sucessional e, ao mesmo tempo, uma produção escalonada e diversificada. Essa é uma estratégia de conciliação entre recuperação ambiental e produção agrícola, pois:",
      choices: ["A) substitui gradativamente as espécies cultiváveis por espécies arbóreas.", "B) intensifica a fertilização do solo com o uso de técnicas apropriadas e biocidas.", "C) promove maior diversidade de vida no solo com o aumento da matéria orgânica.", "D) favorece a dispersão das sementes cultivadas pela fauna residente nas áreas florestais.", "E) cria condições para o estabelecimento de espécies pioneiras com a diminuição da insolação sobre o solo."]
    }, {
      question: "(ENEM 2016) Uma nova estratégia para o controle da dengue foi apresentada durante o Congresso Internacional de Medicina Tropical, no Rio de Janeiro, em 2012. O projeto traz uma abordagem nova e natural para o combate à doença e já está em fase de testes. O objetivo do programa é cessar a transmissão do vírus da dengue pelo Aedes aegypti, a partir da introdução da bactéria Wolbachia – que é naturalmente encontrada em insetos – nas populações locais de mosquitos. Quando essa bactéria é introduzida no A. aegypti, atua como uma “vacina”, estimulando o sistema imunológico e bloqueando a multiplicação do vírus dentro do inseto. Qual o conceito fundamental relacionado a essa estratégia?",
      choices: ["A) Clonagem.", "B) Mutualismo.", "C) Parasitismo.", "D) Transgênese.", "E) Controle biológico."]
    }, {
      question: "(Enem-2018) As abelhas utilizam a sinalização química para distinguir a abelha-rainha de uma operária, sendo capazes de reconhecer diferenças entre moléculas. A rainha produz o sinalizador químico conhecido como ácido 9-hidroxidec-2-enoico, enquanto as abelhas-operárias produzem o ácido 10-hidroxidec-2-enoico. Nós podemos distinguir as abelhas-operárias e rainhas por sua aparência, mas, entre si, elas usam essa sinalização química para perceber a diferença. Pode-se dizer que veem por meio da química. As moléculas dos sinalizadores químicos produzidas pelas abelhas rainha e operária possuem diferença na:",
      choices: ["A) fórmula estrutural.", "B) fórmula molecular.", "C) identificação dos tipos de ligação.", "D) contagem do número de carbonos.", "E) identificação dos grupos funcionais."]
    }, {
      question: "(Enem-2017) A técnica do carbono-14 permite a datação de fósseis pela medição dos valores de emissão beta desse isótopo presente no fóssil. Para um ser em vida, o máximo são 15 emissões beta/(min g). Após a morte, a quantidade de 14C se reduz pela metade a cada 5 730 anos. Considere que um fragmento fóssil de massa igual a 30 g foi encontrado em um sítio arqueológico, e a medição de radiação apresentou 6 750 emissões beta por hora. A idade desse fóssil, em anos, é:",
      choices: ["A) 450.", "B) 1 433.", "C) 11 460.", "D) 17 190.", "E) 27 000."]
    }, {
      question: "(Enem-2018) Companhias que fabricam jeans usam cloro para o clareamento, seguido de lavagem. Algumas estão substituindo o cloro por substâncias ambientalmente mais seguras como peróxidos, que podem ser degradados por enzimas chamadas peroxidases. Pensando nisso, pesquisadores inseriram genes codificadores de peroxidases em leveduras cultivadas nas condições de clareamento e lavagem dos jeans e selecionaram as sobreviventes para produção dessas enzimas. TORTORA, G.J.; FUNKE, B.R.; CASE, C.L. Microbiologia. Rio de Janeiro: Artmed, 2016 (adaptado). Nesse caso, o uso dessas leveduras modificadas objetiva:",
      choices: ["A) reduzir a quantidade de resíduos tóxicos nos efluentes da lavagem.", "B) eliminar a necessidade de tratamento da água consumida.", "C) elevar a capacidade de clareamento dos jeans.", "D) aumentar a resistência do jeans a peróxidos.", "E) associar ação bactericida ao clareamento."]
    }, {
      question: "(ENEM) A trajetória de Liesel Meminger é contada por uma narradora mórbida, surpreendentemente simpática. Ao perceber que a pequena ladra de livros lhe escapa, a Morte afeiçoa-se à menina e rastreia suas pegadas de 1939 a 1943. Traços de uma sobrevivente: a mãe comunista, perseguida pelo nazismo, envia Liesel e o irmão para o subúrbio pobre de uma cidade alemã, onde um casal se dispõe a adotá-los por dinheiro. O garoto morre no trajeto e é enterrado por um coveiro que deixa cair um livro na neve. É o primeiro de uma série que a menina vai surrupiar ao longo dos anos. O único vínculo com a família é esta obra, que ela ainda não sabe ler. A vida ao redor é a pseudorrealidade criada em torno do culto a Hitler na Segunda Guerra. Ela assiste à eufórica celebração do aniversário do Führer pela vizinhança. A Morte, perplexa diante da violência humana, dá um tom leve e divertido à narrativa deste duro confronto entre a infância perdida e a crueldade do mundo adulto, um sucesso absoluto – e raro – de crítica e público. Os gêneros textuais podem ser caracterizados, dentre outros fatores, por seus objetivos. Esse fragmento é um(a):",
      choices: ["A) reportagem, pois busca convencer o interlocutor da tese defendida ao longo do texto.", "B) resumo, pois promove o contato rápido do leitor com uma informação desconhecida.", "C) sinopse, pois sintetiza as informações relevantes de uma obra de modo impessoal.", "D) instrução, pois ensina algo por meio de explicações sobre uma obra específica.", "E) resenha, pois apresenta uma produção intelectual de forma crítica."]
    }, {
      question: "(ENEM)  Menina  A máquina de costura avançava decidida sobre o pano, Que bonita que a mãe era, com os alfinetes na boca. Gostava de olhá-la calada, estudando seus gestos, enquanto recortava retalhos de pano com a tesoura. Interrompia às vezes seu trabalho, era quando a mãe precisava da tesoura. Admirava o jeito decidido da mãe ao cortar pano, não hesitava nunca, nem errava. A mãe sabia tanto! Tita chamava-a de ( ) como quem diz ( ). Tentava não pensar as palavras, mas sabia que na mesma hora da tentativa tinha-as pensado. Oh, tudo era tão difícil. A mãe saberia o que ela queria perguntar-lhe intensamente agora quase com fome depressa depressa antes de morrer, tanto que não se conteve e — Mamãe, o que é desquitada? — atirou rápida com uma voz sem timbre. Tudo ficou suspenso, se alguém gritasse o mundo acabava ou Deus aparecia — sentia Ana Lúcia. Era muito forte aquele instante, forte demais para uma menina, a mãe parada com a tesoura no ar, tudo sem solução podendo desabar a qualquer pensamento, a máquina avançando desgo – vernada sobre o vestido de seda brilhante espalhando luz luz luz. ÂNGELO. I. Menina. In: A face horrível. São Paulo: Lazuli, 2017. Escrita na década de 1960, a narrativa põe em evidência uma dramaticidade centrada na:",
      choices: ["A) insinuação da lacuna familiar gerada pela ausência da figura paterna.", "B) associação entre a angústia da menina e a reação intempestiva da mãe.", "C) relação conflituosa entre o trabalho doméstico e a emancipação feminina.", "D) representação de estigmas sociais modulados pela perspectiva da criança.", "E) expressão de dúvidas existenciais intensificadas pela percepção do abandono."]
    }, {
      question: "(ENEM) 1. Nós queremos cantar o amor ao perigo, o hábito da energia e da temeridade.  2. A coragem, a audácia, a rebelião serão elementos essenciais de nossa poesia.  3. A literatura exaltou até hoje a imobilidade pensativa, o êxtase, o sono. Nós queremos exaltar o movimento agressivo, a insônia febril, o passo de corrida, o salto mortal, o bofetão e o soco.  4. Nós afirmamos que a magnificência do mundo enriqueceu-se de uma beleza nova: a beleza da velocidade. Um automóvel de corrida com seu cofre enfeitado com tubos grossos, semelhantes a serpentes de hálito explosivo… um automóvel rugidor, que parece correr sobre a metralha, é mais bonito que a Vitória de Samotrácia.  5. Nós queremos entoar hinos ao homem que segura o volante, cuja haste ideal atravessa a Terra, lançada também numa corrida sobre o circuito da sua órbita.  6. É preciso que o poeta prodigalize com ardor, fausto e munificiência, para aumentar o entusiástico fervor dos elementos primordiais.  MARINETTI, F. T. Manifesto futurista. In: TELES, G. M. Vanguardas europeias e Modernismo brasileiro. Petrópolis: Vozes, 1985.  O documento de Marinetti, de 1909, propõe os referenciais estéticos do Futurismo, que valorizam a",
      choices: ["A) composição estática.", "B) inovação tecnológica.", "C) suspensão do tempo.", "D) retomada do helenismo.", "E) manutenção das tradições."]
    }, {
      question: "(ENEM) HELOÍSA: Faz versos?  PINOTE: Sendo preciso… Quadrinhas… Acrósticos… Sonetos… Reclames.  HELOÍSA: Futuristas?  PINOTE: Não senhora! Eu já fui futurista. Cheguei a acreditar na independência… Mas foi uma tragédia! Começaram a me tratar de maluco. A me olhar de esguelha. A não me receber mais. As crianças choravam em casa. Tenho três filhos. No jornal também não pagavam, devido à crise. Precisei viver de bicos. Ah! Reneguei tudo. Arranjei aquele instrumento (Mostra a faca) e fiquei passadista.  ANDRADE, O. O rei da vela. São Paulo: Globo, 2003.  O fragmento da peça teatral de Oswald de Andrade ironiza a reação da sociedade brasileira dos anos 1930 diante de determinada vanguarda europeia. Nessa visão, atribui-se ao público leitor uma postura:",
      choices: ["A) preconceituosa, ao evitar formas poéticas simplificadas.", "B) conservadora, ao optar por modelos consagrados.", "C) preciosista, ao preferir modelos literários eruditos.", "D) nacionalista, ao negar modelos estrangeiros.", "E) eclética, ao aceitar diversos estilos poéticos."]
    }, {
      question: "(ENEM) Zé Araújo começou a cantar num tom triste, dizendo aos curiosos que começaram a chegar que uma mulher tinha se ajoelhado aos pés da santa cruz e jurado em nome de Jesus um grande  amor, mas jurou e não cumpriu,  fingiu e me enganou, pra mim você mentiu, pra Deus você pecou, o coração tem razões que a própria razão desconhece, faz promessas e juras, depois esquece. O caboclo estava triste e inspirado. Depois dessa canção que arrepiou os cabelos da Neusa, emendou com uma valsa mais arretada ainda, cheia de palavras difíceis, mas bonita que só a gota serena. Era a história de uma boneca encantadora vista numa vitrine de cristal sobre o soberbo pedestal. Zé Araújo fechava os olhos e soltava a voz: Seus cabelos tinham a cor/ Do sol a irradiar/ Fulvos raios de amor./ Seus olhos eram circúnvagos/ Do romantismo azul dos lagos/ Mãos liriais, uns braços divinais,/ Um corpo alvo sem par/ E os pés muito pequenos./Enfim eu vi nesta boneca/ Uma perfeita Vênus.   CASTRO, N. L. As pelejas de Ojuara o homem que desafiou o diabo. São Paulo: Arx, 2006 (adaptado).  O comentário do narrador do romance “[…] emendou com uma valsa mais arretada ainda, cheia de palavras difíceis, mas bonita que só a gota serena” relaciona-se ao fato de que essa valsa é representativa de uma variedade linguística:",
      choices: ["A) detentora de grande prestígio social.", "B) específica da modalidade oral da língua.", "C) previsível para o contexto social da narrativa.", "D) constituída de construções sintáticas complexas.", "E) valorizadora do conteúdo em detrimento da forma."]
    }, {
      question: "(ENEM) A agricultura ecológica e a produção orgânica de alimentos estão ganhando relevância em diferentes partes do mundo. No campo brasileiro, também acontece o mesmo. Impulsionado especialmente pela expansão da demanda de alimentos saudáveis, o setor cresce a cada ano, embora permaneça relativamente marginalizado na agenda de prioridades da política agrícola praticada no país.  AQUINO, J. R.; GAZOLLA, M.; SCHNEIDER, S. In: SAMBUICHI, R. H. R. et al. (Org.). A política nacional de agroecologia e produção orgânica no Brasil: uma trajetória de luta pelo desenvolvimento rural sustentável. Brasília: Ipea, 2017 (adaptado).  Que tipo de intervenção do poder público no espaço rural é capaz de reduzir a marginalização produtiva apresentada no texto?",
      choices: ["A) Subsidiar os cultivos de base familiar.", "B) Favorecer as práticas de fertilização química.", "C) Restringir o emprego de maquinário moderno.", "D) Controlar a expansão de sistemas de irrigação.", "E) Regulamentar o uso de sementes selecionadas."]
    }, {
      question: "(ENEM) Não é verdade que estão ainda cheios de velhice espiritual aqueles que nos dizem: “Que fazia Deus antes de criar o céu e a terra? Se estava ocioso e na realizava”, dizem eles, “por que não ficou sempre assim no decurso dos séculos, abstendo-se, como antes, de toda ação? Se existiu em Deus um novo movimento, uma vontade nova para dar o ser a criaturas que nunca antes criar, como pode haver verdadeira eternidade, se nele aparece uma vontade que antes não existia?” A questão da eternidade, tal como abordada pelo autor, é um exemplo de reflexão filosófica sobre a(s):",
      choices: ["A) essência de ética cristã.", "B) natureza universal da tradição.", "C) certezas inabaláveis da experiência.", "D) abrangência da compreensão humana.", "E) interpretações da realidade circundante."]
    }, {
      question: "(ENEM) Rodrigo havia sido indicado pela oposição para fiscal duma das mesas eleitorais. Põs o revólver na cintura, uma caixa de balas no bolso e encaminhou-se para seu posto. A chamada dos eleitores começou às sete da manhã. Plantados junto da porta, os capangas do Trindade ofereciam cédulas com o nome dos candidatos oficiais a todos os eleitores que entravam. Estes, em sua quase totalidade, tomavam docilmente dos papeluchos e depositavam-nos na urna, depois de assinar a autêntica. Os que se recusavam a isso tinham seus nomes acintosamente anotados.  VERISSIMO, E. O tempo e o vento. São Paulo: Globo, 2003 (adaptado).  Erico Veríssimo tematiza em obra ficcional o seguinte aspecto característico da vida política durante ae Primeira República:",
      choices: ["A) Identificação forçada de homens analfabetos.", "B) Monitoramento legal dos pleitos legislativos.", "C) Repressão explícita ao exercício de direito.", "D) Propaganda direcionada à população do campo.", "E) Cerceamento policial dos operários sindicalizados."]
    }, {
      question: "(ENEM) No início da década de 1990, dois biólogos importantes, Redford e Robinson, produziram um modelo largamente aceito de produção sustentável que previa quantos indivíduos de cada espécie poderiam ser caçados de forma sustentável baseado nas suas taxas de reprodução. Os seringueiros do Alto Juruá tinham um modelo diferente: a quem lhes afirmava que estavam caçando acima do sustentável (dentro do modelo), eles diziam que não, que o nível da caça dependia da existência de áreas de refúgio em que ninguém caçava. Ora, esse acabou sendo o modelo batizado de fonte-ralo proposto dez anos após o primeiro por Novaro, Bodmer e o próprio Redford e que suplantou o modelo anterior. Fonte: CUNHA, M. C. Revista USP, n. 75,  nov. 2C07. No contexto da produção científica, a necessidade de reconstrução desse modelo, conforme exposto no texto, foi determinada pelo confronto com um(a):",
      choices: ["A) conclusão operacional obtida por lógica dedutiva.", "B) visão de mundo marcada por preconceitos morais.", "C) hábito social condicionado pela religiosidade popular.", "D) conhecimento empírico apropriado pelo senso comum.", "E) padrão de preservação construído por experimentação dirigida."]
    }, {
      question: "(ENEM) Um dos teóricos da democracia moderna, Hans Kelsen, considera elemento essencial da democracia real (não da democracia ideal, que não existe em lugar algum) o método da seleção dos lideres, ou seja, a eleição. Exemplar, neste sentido, é a afirmação de um juiz da Corte Suprema dos Estados Unidos, por ocasião de uma eleição de 1902: A cabine eleitoral é o templo das instituições americanas, onde cada um de nós é um sacerdote, ao qual é confiada a guarda da arca da aliança e cada um oficia do seu próprio altar.  BOBBIO, N. Teoria Geral da política. Rio de Janeiro: Elsovior, 2000 (adaptado).  As metáforas utilizadas no texto referem-se a uma concepção de democracia fundamentada no(a):",
      choices: ["A) justificação teísta do direito.", "B) rigidez da hierarquia de classe.", "C) ênfase formalista na administração.", "D) protagonismo do Executivo no poder.", "E) centralidade do indivíduo na sociedade"]
    }, {
      question: "(ENEM) Então disse: “Este é o local onde construirei. Tudo pode chegar aqui pelo Eufrates, o Tigre e uma rede de canais. Só um lugar como este sustentará o exército e a população geral”. Assim ele traçou e destinou as verbas para a sua construção, e deitou o primeiro tijolo com sua própria mão, dizendo: “Em nome de Deus, e em louvor a Ele. Construí, e que Deus vos abençoe”.  Fonte: AL-TABARI, M. Uma história dos povos árabes.São Paulo: Cia. das Letras, 1995 (adaptado).  A decisão do califa Al-Mansur (754-775) de construir Bagdá nesse local orientou-se pela:",
      choices: ["A) disponibilidade de rotas e terras férteis como base dominação política.", "B) proximidade de áreas populosas como afirmação da superioridade bélica.", "C) submissão à hierarquia e à lei islâmica como controle do poder real.", "D) fuga da península arábica como afastamento dos conflitos sucessórios.", "E) ocupação de região fronteiriça como contenção do avanço mongol."]
    }, {
      question: "(ENEM) A sociedade como um sistema justo de cooperação social consiste em uma das ideias familiares fundamentais, que dá estrutura e organização à justiça como equidade. A cooperação social guia-se por regras e procedimentos publicamente reconhecidos e aceitos por aquele que cooperam como sendo apropriados para regular a sua conduta. Diz-se que a cooperação é justa porque seus termos são tais que todos os participantes podem razoavelmente aceitar, desde que todos os demais também o aceitem. No contexto do pensamento político, a ideia apresentada mostra-se consoante o(a):",
      choices: ["A) ideal republicano de governo.", "B) corrente tripartite dos poderes.", "C) posicionamento crítico do socialismo.", "D) legitimidade do absolutismo monárquico.", "E) entendimento do contratualismo moderno."]
    }, {
      question: "(ENEM) No caso do Departamento de Defesa dos Estados Unidos, a ênfase está posta no traçado de uma estratégia geral de desarticulação, não só dos inimigos reais como dos potenciais, inserida na concepção preventiva que supõe que a mínima dissidência é um sinal de perigo e de guerra futura. Deve-se ter capacidade para responder a uma guerra convencional tanto quanto para enfrentar um inimigo difuso, atentando simultaneamente para todas as áreas geográficas do planeta. Trata-se, sem dúvida, da estratégia com pretensões mais abrangentes que se desenvolveu até agora.Tomando o texto como parâmetro, qual tendência contemporânea impulsiona a formulação de estratégias mais abrangentes por parte do Estado americano?",
      choices: ["A) Erradicação dos conflitos em territórios.", "B) Propagação de organizações em redes.", "C) Eliminação das diferenças regionais.", "D) Ampliação de modelo democrático.", "E) Projeção da diplomacia mundial."]
    }, {
      question: "(ENEM) “A principal característica da situação social dos angloamericanos é seu caráter eminentemente democrático. Afirmei anteriormente que reinava uma igualdade muito grande entre os emigrantes que foram se estabelecer na Nova Inglaterra. Para isso contribuiu a influência das leis de sucessão. Estabelecidas de uma maneira, as leis de sucessão reúnem, concentram e agrupam em um só a propriedade e o poder. Estabelecidas por outros princípios, produzem o oposto: dividem, partilham e disseminam os bens e o poder.”O texto tematiza o papel desempenhado por uma norma na criação de um ambiente propicio ao(à):",
      choices: ["A) emprego do trabalho escravo.", "B) consolidação dos valores burgueses.", "C) banimento das dissidências religiosas.", "D) contenção da identificação nacionalista.", "E) hierarquização dos agentes econômicos."]
    }, {
      question: "(ENEM) Ao abrigo do teto, sua jornada de fé começava na sala de jantar. Na pequena célula cristã, dividia-se a refeição e durante elas os crentes conversavam, rezavam e liam cartas de correligionários residentes em locais diferentes do Império Romano (século II da Era Cristã). Esse ambiente garantia peculiar apoio emocional às experiências intensamente individuais que abrigava.Um motivo que explica a ambientação da prática descrita no texto encontra-se no(a):",
      choices: ["A) regra judaica, que pregava a superioridade espiritual dos cultos das sinagogas.", "B) moralismo da legislação, que dificultava as reuniões abertas da juventude livre.", "C) adesão do patriarcado, que subvertia o conceito original dos valores estrangeiros.", "D) decisão política, que censurava as manifestações públicas da doutrina dissidente.", "E) violência senhorial, que impunha a desestruturação forçada das famílias escravas."]
    }, {
      question: "(ENEM) A Educação Nova, alargando a sua finalidade para além dos limites das classes, assume, com uma feição mais humana, a sua verdadeira função social, preparando-se para formar “a hierarquia democrática” pela “hierarquia das capacidades”, recrutadas em todos os grupos sociais, a que se abrem as mesmas oportunidades de educação. Ela tem, por objeto, organizar e desenvolver os meios de ação durável com o fim de “dirigir os desenvolvimentos natural e integral do ser humano em cada uma das etapas de seu crescimento”, de acordo com uma certa concepção do mundo.Os autores do manifesto citado procuravam contrapor-se ao caráter oligárquico da sociedade brasileira. Nesse sentido, o trecho propõe uma relação necessária entre:",
      choices: ["A) ensino técnico e mercado de trabalho.", "B) acesso à escola e valorização do mérito.", "C) ampliação de vagas e formação de gestores.", "D) disponibilidade de financiamento e pesquisa avançada.", "E) remuneração de professores e extinção do analfabetismo."]
    }, {
      question: "(ENEM) É preciso usar de violência e rebater varonilmente os apetites dos sentidos sem atender ao que a carne quer ou não quer, mas trabalhando por sujeitá-la ao espírito, ainda que se revolte. Cumpre castigá-la e curvá-la à sujeição, a tal ponto que esteja disposta para tudo, sabendo contentar-se com pouco e deleitar-se com a simplicidade, sem resmungar por qualquer incômodo.Qual característica do ascetismo medieval é destacada no texto?",
      choices: ["A) Exaltação do ritualismo litúrgico.", "B) Afirmação do pensamento racional.", "C) Desqualificação da atividade laboral.", "D) Condenação da alimentação impura.", "E) Desvalorização da materialidade corpórea."]
    }, {
      question: "(ENEM) Minha fórmula para o que há de grande no individuo é amor fati: nada desejar além daquilo que é, nem diante de si, nem atrás de si, nem nos séculos dos séculos. Não se contentar em suportar o inelutável, e ainda menos dissimula-lo, mas amá-lo.Essa fórmula indicada por Nietzsche consiste em uma crítica à tradição cristã que:",
      choices: ["A) combate as práticas sociais de cunho afetivo.", "B) impede o avanço científico no contexto moderno.", "C) associa os cultos pagãos à sacralização da natureza.", "D) condena os modelos filosóficos da Antiguidade Clássica.", "E) consagra a realização humana ao campo transcendental."]
    }, {
      question: "(ENEM) Nos setores mais altamente desenvolvidos da sociedade contemporânea, o transplante de necessidades sociais para individuais é de tal modo eficaz que a diferença entre elas parece puramente teórica. As criaturas se reconhecem em suas mercadorias; encontram sua alma em seu automóvel, casa em patamares, utensílios de cozinha.O texto indica que, no capitalismo, a satisfação dos desejos pessoais é influenciada por:",
      choices: ["A) políticas estatais de divulgação.", "B) incentivos controlados de consumo.", "C) prescrições coletivas de organizacão.", "D) mecanismos subjetivos de identificação.", "E) repressões racionalizada no narcizismo."]
    }, {
      question: "(ENEM) Famoso por ser o encantador de viúvas da cidade de Cabaceiras, na Paraíba, Zé de Sila é um contador de histórias parecido com o personagem Chicó, do 'Auto da Compadecida'. Ele defende veementemente que a oração da avó sustentava mais a chuva. 'Quando era pequeno e chovia por aqui, ajudava minha avó colocando os pratos emborcados no terreiro para diminuir o vento. Ela fazia isso e rezava para a chuva durar mais', diz Zé de Sila.Ao destacar expressões e vivências populares do cotidiano, o texto mobiliza os seguintes aspectos da diversidade regional:",
      choices: ["A) alianças afetivas conectadas ao ritual matrimonial.", "B) práticas místicas associadas ao patrimônio cultural.", "C) manifestações teatrais atreladas ao imaginário político.", "D) narrativas fílmicas relacionadas às intempéries climáticas.", "E) argumentações literárias interligadas as catástrofes ambientais."]
    }, {
      question: "(ENEM) As grandes empresas seriam certamente, representação de um exercício de poder, ante o grau de autonomia de ação de que dispõe. O que se pretende salientar é a ideia de que enclave plantas industriais que estabelecem relações escassas com o entorno, mas exercem grande influência na economia extralocal.Que tipo de ação tomada por empresas reflete a forma de territorialização da produção industrial apresentada no texto?",
      choices: ["A) criação de vilas operárias.", "B) promoção de eventos comunitários.", "C) recuperação de áreas degradadas.", "D) incorporação de saberes tradicionais.", "E) importação de mão de obra qualificada."]
    }, {
      question: "(ENEM) Desde o século XII que a cristandade ocidental era agitada pelo desafio lançado pelacultura profana -- a dos romances de cavalaria, mas também a cultura folclórica dos camponeses e igualmente a dos citadinos, de caráter mais jurídico -- à cultura eclediástica, cujo veiculo era o latim. Francisco de Assis veio alterar a situação, propondo aos seus ouvintes uma mensagem acessível a todos e, simultaneamente, enobrecendo a língua vulgar através do seu uso na religião.O comportamento desses religiosos demonstra uma preocupação com as características assumidas pela igreja e com as desigualdades sociais compartilhada no seu tempo pelos(as):",
      choices: ["A) senhores feudais.", "B) movimentos heréticos.", "C) integrantes das cruzadas.", "D) corporações de ofícios.", "E) universidades medievais."]
    }, {
      question: "(ENEM) Se for possível, manda-me dizer  -- É sua cheia. A cada está vazia --  Manda-me dizer, e o paraíso Há de ficar mais perto, e mais recente Mas há de parecer seu rosto incerto. Manda-me buscar se tens o dia Tão longo como a noite. Se é verdade Que sem mim só vês monotonia. É se te lembras do brilho das marés De alguns peixes rosados Numas águas E dos meus pés molhados, manda-me dizer.  -- É lua nova--  E revestida de luz te volto a ver. Falando ao outro, o eu lírico revela-se focalizando um desejo que remete ao:",
      choices: ["A) ceticismo quanto a possibilidade do reencontro.", "B) tédio provocado pela distância física do seu amado.", "C) sonho de autorrealização desenhado pela memória.", "D) julgamento implícito das atitudes de quem se afasta.", "E) questionamento sobre o significado do amor ausente."]
    }, {
      question: "(ENEM) TEXTO I:Os meus pensamentos são todos sensações. Penso com os olhos e com os ouvidos E com as mãos e os pés E com o nariz e a boca.  PESSOA, F. O guardador de rebanhos – IX. In: GALHOZ, M. A. (Org.). Obras poéticas. Rio de Janeiro: Nova Aguilar, 1999 (fragmento).  TEXTO II:Tudo aquilo que sei do mundo, mesmo por ciência, eu o sei a partir de uma visão minha ou de uma experiência do mundo sem a qual os símbolos da ciência não poderiam dizer nada.  MERLEAU-PONTY, M. Fenomenologia da percepção. São Paulo: Martins Fontes, 1999 (adaptado).  Os textos mostram-se alinhados a um entendimento acerca da ideia de conhecimento, numa perspectiva que ampara a:",
      choices: ["A) anterioridade da razão no domínio cognitivo.", "B) confirmação da existência de saberes inatos.", "C) valorização do corpo na apreensão da realidade.", "D) verificabilidade de proposições no campo da lógica.", "E) possibilidade de contemplação de verdades atemporais."]
    }, {
      question: "(ENEM) Exterior: Between The Museums – Day:CELINE Americans always think Europe is perfect. But such beauty and history can be really oppressive. It reduces the individual to nothing. It just reminds you all the time you are just a little speck in a long history, where in America you feel like you could be making history. That’s why I like Los Angeles because it is so…  (JESSE)  Ugly?  (CELINE)  No, I was going to say “neutral”. It’s like looking at a blank canvas. I think people go to places like Venice on their honeymoon to make sure they are not going to fight for the first two weeks of their marriage because they’ll be too busy looking around at all the beautiful things. That’s what people call a romantic place – somewhere where the prettiness will contain your primary violent instinct. A real good honeymoon spot would be like somewhere in New Jersey.Considerando-se o olhar dos personagens, esse trecho do roteiro de um filme permite reconhecer que a avaliação sobre um lugar depende do(a):",
      choices: ["A) beleza do próprio local.", "B) perspectiva do visitante.", "C) contexto histórico do local.", "D) tempo de permanência no local.", "E) finalidade da viagem do visitante."]
    }, {
      question: "(ENEM, 2017) One of the things that made an incredible impression on me in the film was Frida’s comfort in and celebration of her own unique beauty. She didn’t try to fit into conventional ideas or images about womanhood or what makes someone or something beautiful. Instead, she fully inhabited her own unique gifts, not particularly caring what other people thought. She was magnetic and beautiful in her own right. She painted for years, not to be a commercial success or to be discovered, but to express her own inner pain, joy, family, love and culture. She absolutely and resolutely was who she was. The trueness of her own unique vision and her ability to stand firmly in her own truth was what made her successful in the end.  (HUTZLER, L.)  A autora desse comentário sobre o filme Frida mostra-se impressionada com o fato de a pintora",
      choices: ["A) ter uma aparência exótica.", "B) vender bem a sua imagem.", "C) ter grande poder de sedução.", "D) assumir sua beleza singular.", "E) recriar-se por meio da pintura."]
    }, {
      question: "(ENEM, 2010)  Viva la Vida  I used to rule the world Seas would rise when I gave the word Now in the morning and I sleep alone Sweep the streets I used to know I use to roll the dice Feel the fear in my enemy’s eyes Listen as the crowd would sing “Now the old king is dead! Long live the king!” One minute I held the key Next the walls were closed on me And I discovered that my castles stand Upon pillars of salt and pillars of sand.  MARTIN, C. Viva la Vida, Coldplay. In: Viva la Vida or Death and all his friends. Parlophone, 2008.  Letras de músicas abordam temas que, de certa forma, podem ser reforçados pela repetição de trechos ou palavras. O fragmento da canção Viva la Vida, por exemplo, permite conhecer o relato de alguém que:",
      choices: ["A) costumava ter o mundo aos seus pés e, de repente, se viu sem nada.", "B) almeja o título de rei e, por ele, tem enfrentado inúmeros inimigos.", "C) causa pouco temor a seus inimigos, embora tenha muito poder.", "D) limpava as ruas e, com seu esforço, tornou-se rei de seu povo.", "E) tinha a chave para todos os castelos nos quais desejava morar."]
    }, {
      question: "(ENEM, 2018)  1984 (excerpt)  ‘Is it your opinion, Winston, that the past has real existence?’ [...] O’Brien smiled faintly. ‘I will put it more precisely. Does the past exist concretely, in space? Is there somewhere or other a place, a world of solid objects, where the past is still happening?’  ‘No.’  ‘Then where does the past exist, is at all?’ ‘In records. It is written down.’ ‘In records. And ___?’ ‘In the mind. In human memories.’ ‘In memory. Very well, then. We, the Party, control all records, and we control all memories. Then we control the past, do we not?’  ORWELL, G. Nineteen Eighty-Four. New York: Signet Classics, 1977.  O romance 1984 descreve os perigos de um Estado totalitário. A ideia evidenciada nessa passagem é que o controle do Estado se dá por meio do(a):",
      choices: ["A) boicote a ideais libertários.", "B) veto ao culto das tradições.", "C) poder sobre memórias e registros.", "D) censura a produções orais e escritas.", "E) manipulação de pensamentos individuais."]
    }, {
      question: "(ENEM, 2020) Finally, Aisha finished with her customer and asked what colour Ifemelu wanted for her hair attachments. “Colour four.” “Not good colour,” Aisha said promptly. “That’s what I use.” “It look dirty. You don’t want colour one?” “Colour one it too black. It looks fake,” Ifemelu said, loosening her headwrap. “Sometimes I use colour two, but colour four is closest to my natural colour.”[...] She touched Ifemelu’s hair. “Why you don’t have relaxer?” “I like my hair the way God made it.” “But how do you comb it? Hard to comb,” Aisha said. Ifemelu had brought her own comb. She gently combed her hair, dense, soft and tightly coiled, until it framed her head like a halo. “It’s not hard to comb if you moisturize it properly,” she said, slipping into the coaxing tone of the proselytizer that she used whenever she was trying to convince other black women about the merits of wearing their hair natural. Aisha snorted; she clearly could not understand why anybody would choose to suffer through combing natural hair, plucked a little attachment from the pile on the table ad began deftly to twist.  ADICHIE, C. Americanah: A novel. New York: Anchor Books, 2013.  A passagem do romance da escritora nigeriana traz um diálogo entre duas mulheres negras: a cabeleireira, Aisha, e a cliente, Ifemelu. O posicionamento da cliente é sustentado por argumentos que:",
      choices: ["A) reforçam um padrão de beleza.", "B) retratam um conflito de gerações.", "C) revelam uma atitude de resistência.", "D) demonstram uma postura de imaturidade.", "E) evidenciam uma mudança de comportamento."]
    }, {
      question: "(ENEM, 2016) BOGOF is used as a noun as in ‘There are some great bogofs on at the supermarket’ ou an adjective, usually with a word such as ‘offer’ or ‘deal’ — ‘there are some great bogof offers in store’. When you combine the first letters of the words in a phrase or the name of an organisation, you have an acronym. Acronyms are spoken as a word so NATO (North Atlantic Treaty Organisation) is not pronounced N-A-T-O. We say NATO. Bogof, when said out loud, is quite comical for a native speaker, as it sounds like an insult, ‘Bog off!’, meaning go away, leave me alone, slightly childish and a little old-fashioned. BOGOF is the best-known of the supermarket marketing strategies. The concept was first imported from the USA during the 1970s recession, when the food prices were very high. It came back into fashion in the late 1990s, led by big supermarket chains trying to gain a competitive advantage over each other. Consumers were attracted by the idea that they could get something for nothing. Who could possibly say ‘no’?  Acesso em: 2 ago, 2012 (adaptado)  Considerando-se as informações do texto, a expressão “bogof” é usada para:",
      choices: ["A) anunciar mercadorias em promoção.", "B) pedir para uma pessoa se retirar.", "C) comprar produtos fora de moda.", "D) indicar recessão na economia.", "E) chamar alguém em voz alta."]
    }, {
      question: "(ENEM, 2019) 5 Ways Pets Can Improve Your Health A pet is certainly a great friend. After a difficult day, pet owners quite literally fell the love. In fact, for nearly 25 years, research has shown that living with pets provides certain health benefits. Pets help lower blood pressure and lessen anxiety. They boost our immunity. They can even help you get dates. Allergy Fighters: A growing number of studies have suggested that kids growing up in a home with “furred animals” will have less risk of allergies and asthma. Date magnets: Dogs are great for making love connections. Forget Internet matchmaking — a dog is a natural conversation starter. Dogs for the Aged: Walking a dog or just caring for a pet — for elderly people who are able — can provide exercise and companionship. Good for Mind and Soul: Like any enjoyable activity, playing with a dog can elevate levels of serotonin and dopamine — nerve transmitters that are known to have pleasurable and calming properties. Good for the Heart: Heart attack patients who have pets survive longer than those without, according to several studies.  DAVIS, J. L. Acesso em: 21 abr. 2013 (adaptado).  Ao discutir sobre a influência de animais de estimação no bem-estar do ser humano, a autora, a fim de fortalecer seus argumentos, utiliza palavras e expressões como research, a growing number of research e several studies com o objetivo de:",
      choices: ["A) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.", "B) convencer sobre os benefícios da adoção de animais de estimação para a saúde.", "C) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.", "D) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.", "E) esclarecer sobre o modo como idosos devem se relacionar com animais de estimação."]
    }, {
      question: "(ENEM - 2017)  As centrífugas são equipamentos utilizados em laboratórios, clínicas e indústrias. Seu funcionamento faz uso da aceleração centrífuga obtida pela rotação de um recipiente e que serve para a separação de sólidos em suspensão em líquidos ou de líquidos misturados entre si.  RODITI. I. Dicionário Houaiss de física. Rio de Janeiro: Objetiva, 2005 (adaptado).  Nesse aparelho, a separação das substâncias ocorre em função",
      choices: ["A) das diferentes densidades.", "B) dos diferentes raios de rotação.", "C)das diferentes velocidades angulares.", "D) das diferentes quantidades de cada substância.", "E) da diferente coesão molecular de cada substância."]
    }, {
      question: "(ENEM - 2021) Com o aumento da população de suínos no Brasil, torna-se necessária a adoção de métodos para reduzir o potencial poluidor dos resíduos dessa agroindústria, uma vez que, comparativamente ao esgoto doméstico, os dejetos suínos são 200 vezes mais poluentes. Sendo assim, a utilização desses resíduos como matéria-prima na obtenção de combustíveis é uma alternativa que permite diversificar a matriz energética nacional, ao mesmo tempo em que parte dos recursos hídricos do país são preservados.  BECK, A. M. Resíduos suínos como alternativa energética sustentável. XVII Encontro Nacional de Engenharia de Produção. Anis ENEGEP, Fox do Iguaçu, 2007 (adaptado).  O biocombustível a que se refere o texto é o:",
      choices: ["A) etanol.", "B) biogás.", "C) butano.", "D) metanol.", "E) biodiesel."]
    }, {
      question: "(Enem/2019) Em um determinado ano, os computadores da receita federal de um país identificaram como inconsistentes 20% das declarações de imposto de renda que lhe foram encaminhadas. Uma declaração é classificada como inconsistente quando apresenta algum tipo de erro ou conflito nas informações prestadas. Essas declarações consideradas inconsistentes foram analisadas pelos auditores, que constataram que 25% delas eram fraudulentas. Constatou-se ainda que, dentre as declarações que não apresentaram inconsistências, 6,25% eram fraudulentas. Qual é a probabilidade de, nesse ano, a declaração de um contribuinte ser considerada inconsistente, dado que ela era fraudulenta?",
      choices: ["A) 0,0500.", "B) 0,1000.", "C) 0,1125.", "D) 0,3125.", "E) 0,5000."]
    }, {
      question: "(Enem/2021)É preciso ressaltar que, de todas as capitanias brasileiras, Minas era a mais urbanizada. Não havia ali hegemonia de um ou dois grandes centros. A região era repleta de vilas e arraiais, grandes e pequenos, em cujas ruas muita gente circulava. As regiões da América portuguesa tiveram distintas lógicas de ocupação. Uma explicação para a especificidade da região descrita no texto está identificada na:",
      choices: ["A) apropriação cultural diante das influências externas.", "B) produção manufatureira diante do exclusivo comercial.", "C) insubordinação religiosa diante da hierarquia eclesiástica.", "D) fiscalização estatal diante das particularidades econômicas.", "E) autonomia administrativa diante das instituições metropolitanas."]
    }, {
      question: "(PUC RS)  Diversas plantas da família das aráceas, como o copo-de-leite (Zantedeschia aethiopica) e a comigo-ninguém-pode (Diffenbachia sanguine), são tóxicas, embora populares em jardins e interiores. Por essa razão, às vezes acontecem casos de intoxicação após ingestão de folhas dessas plantas, principalmente envolvendo crianças pequenas. Sua toxicidade advém da presença de ráfides, que são cristais microscópicos de oxalato de cálcio (CaC2O4) em forma de agulhas. Quando o vegetal é ingerido, essas ráfides penetram dolorosamente nos lábios, na língua, na garganta e em outros tecidos, causando sensação de queimação, inchaço e, por vezes, asfixia. Assim, a planta conta com um mecanismo de defesa eficaz contra herbívoros. Sobre esse assunto, é correto afirmar que:",
      choices: ["A) o oxalato de cálcio é um composto iônico com ânions de carga –2.", "B) a ligação química no CaC2O4 é metálica, porque o Ca é um metal alcalino-terroso.", "C) a reação entre ácido oxálico (H2C2O4) e soda cáustica produz o CaC2O4.", "D) a carga dos íons oxalato, no oxalato de ferro(III), seria –3.", "E) o ácido oxálico (H2C2O4) apresenta apenas um hidrogênio ionizável."]
    }, {
      question: "(ENEM) Alguns fenômenos observados no cotidiano estão relacionados com as mudanças ocorridas no estado físico da matéria. Por exemplo, no sistema constituído por água em um recipiente de barro, a água mantém-se fresca mesmo em dias quentes. A explicação para o fenômeno descrito é que, nas proximidades da superfície do recipiente, a:",
      choices: ["A) condensação do líquido libera energia para o meio.", "B) solidificação do líquido libera energia para o meio.", "C) evaporação do líquido retira energia do sistema.", "D) sublimação do sólido retira energia do sistema.", "E) fusão do sólido retira energia do sistema."]
    }, {
      question: "(ENEM)  As indústrias de cerâmica utilizam argila para produzir artefatos como tijolos e telhas. Uma amostra de argila contém 45% em massa de sílica (SiO2) e 10% em massa de água (H2O). Durante a secagem por aquecimento em uma estufa, somente a umidade é removida. Após o processo de secagem, o teor de sílica na argila seca será de:",
      choices: ["A) 45%.", "B) 50%.", "C) 55%.", "D) 90%.", "E) 100%."]
    }, {
      question: "(FATEC SP) Um vazamento de gás dentro do complexo do Porto de Santos liberou uma nuvem tóxica que atingiu duas cidades do litoral de São Paulo. A Companhia Docas do Estado de São Paulo (CODESP), responsável pela área, afirma que se trata de um vazamento do composto dicloroisocianurato de sódio (C3O3N3NaCl2). O produto é usado, na maioria das vezes, para a desinfecção de água, pois libera gás cloro que se dissolve na água, gerando ácido hipocloroso, que apresenta ação bactericida. Ainda de acordo com a companhia, um incêndio ocorrido posteriormente atingiu outros doze contêineres e a área foi isolada. Pouco antes, os bombeiros chegaram a afirmar que a substância que vazou tinha cheiro de amônia, mas a informação não se confirmou.  Acesso em: 28.01.2017. Adaptado.  Assinale a alternativa que mostra a equação química balanceada que representa corretamente a dissolução do gás cloro em água.",
      choices: ["A) Cl (l) + H2O (l) HCl (aq) + O (g).", "B) Cl2 (g) + 2 H2O (l) 4 HCl (aq) + O2 (g).", "C) Cl2 (g) + 2 H2O (l) 2 H2 (g) + Cl2O (g).", "D) Cl2 (g) + H2O (l) HCl (aq) + HClO (aq).", "E) 2 Cl (g) + H2O (l) HCl (aq) + HClO (aq)."]
    }];
    
    var questionCounter = 0; 
    var selections = []; 
    var quiz = $('#quiz'); 
    
     displayNext();
    
    $('#next').on('click', function (e) {
      e.preventDefault();
      
      if(quiz.is(':animated')) {        
        return false;
      }
      choose();
      
      if (isNaN(selections[questionCounter])) {
        alert('Please make a selection!');
      } else {
        questionCounter++;
        displayNext();
      }
    });
    
    $('#prev').on('click', function (e) {
      e.preventDefault();
      
      if(quiz.is(':animated')) {
        return false;
      }
      choose();
      questionCounter--;
      displayNext();
    });
    
    $('#start').on('click', function (e) {
      e.preventDefault();
      
      if(quiz.is(':animated')) {
        return false;
      }
      questionCounter = 0;
      selections = [];
      displayNext();
      $('#start').hide();
    });
    
    $('.button').on('mouseenter', function () {
      $(this).addClass('active');
    });
    $('.button').on('mouseleave', function () {
      $(this).removeClass('active');
    });
    
    function createQuestionElement(index) {
      var qElement = $('<div>', {
        id: 'question'
      });
      
      var header = $('<h2>Question ' + (index + 1) + ':</h2>');
      qElement.append(header);
      
      var question = $('<p>').append(questions[index].question);
      qElement.append(question);
      
      var radioButtons = createRadios(index);
      qElement.append(radioButtons);
      
      return qElement;
    }
    
    function createRadios(index) {
      var radioList = $('<ul>');
      var item;
      var input = '';
      for (var i = 0; i < questions[index].choices.length; i++) {
        item = $('<li>');
        input = '<input type="radio" name="answer" value=' + i + ' />';
        input += questions[index].choices[i];
        item.append(input);
        radioList.append(item);
      }
      return radioList;
    }
    
    function choose() {
      selections[questionCounter] = +$('input[name="answer"]:checked').val();
    }
    
    function displayNext() {
      quiz.fadeOut(function() {
        $('#question').remove();
        
        if(questionCounter < questions.length){
          var nextQuestion = createQuestionElement(questionCounter);
          quiz.append(nextQuestion).fadeIn();
          if (!(isNaN(selections[questionCounter]))) {
            $('input[value='+selections[questionCounter]+']').prop('checked', true);
          }
          
          if(questionCounter === 1){
            $('#prev').show();
          } else if(questionCounter === 0){
            
            $('#prev').hide();
            $('#next').show();
          }
        }else {
          var scoreElem = displayScore();
          quiz.append(scoreElem).fadeIn();
          $('#next').hide();
          $('#prev').hide();
          $('#start').show();
        }
      });
    }
    
    function displayScore() {
      var score = $('<p>',{id: 'question'});
      var matchKit;
      var selection = selections[0] +""+selections[1];
        switch(selection) {

      default:
          matchKit = 'Obrigado por jogar nosso jogo, em breve disponível para Android e IOS.';
    }
      
      score.append('' + matchKit + ' !');
      return score;
    }
  })();